language: python
sudo: true
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

env:
  - RL=330
  - RL=340
  - RL=350
  - RL=3510
  - RL=3530
  - RL=3550

matrix:
  fast_finish: true
  allow_failures:
    - env: RL=330
    - env: RL=340

#TEST
before_install:
  - sudo apt-get update
  - sudo apt-get install -y imagemagick
  - sudo apt-get install -y ghostscript
  - sudo sed -i 's#<policy domain="coder" rights="none" pattern="PDF" />#<policy domain="coder" rights="read|write" pattern="PDF" />#' /etc/ImageMagick-6/policy.xml

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-rl${RL}
  - pip install tox coveralls Sphinx sphinx-rtd-theme

script: tox -e $TOX_ENV
after_success: coveralls $COVERALLS_OPTION

before_script:
  - cd doc/source ; sphinx-build -n -W -b html -d _build/doctrees . _build/html ; cd ../..


