
from PyQt5 import QtCore, QtGui, QtWidgets

import qtmodern.windows
import qtmodern.styles
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 500)
        MainWindow.setStyleSheet("color: #d3d3d3;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("color: #d3d3d3;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 3, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_4.addWidget(self.plainTextEdit_2, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Scrape Custom Data"))
        self.label.setText(_translate("MainWindow", "Enter Tournament URL\'s to Scrape (Tabroom Homepage)"))
        self.label_2.setText(_translate("MainWindow", "Enter Division Keywords"))
        self.pushButton.setText(_translate("MainWindow", "Start Scraping"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Generate Competitor Report"))
        self.label_3.setText(_translate("MainWindow", "Enter Event URL (Tabroom Entries Page)"))
        self.pushButton_3.setText(_translate("MainWindow", "Generate Report"))
        self.groupBox_3.setTitle(_translate("MainWindow", "User Agreement"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "This agreement defines the relationship between You (the User), the Software (this program), and the Company (Offtime Roadmap, LLC). The software may not be relabled or redistributed by You, the User, in any capacity - regardless of whether or not a monetary gain is involved. The Company makes no guarentee, neither explicit nor implicit, regarding the functionality and the long term support of the Software. The company makes no guarentee that the Software will not crash, and by installing the Software, You, the User, agree to the risk of this occuring and are solely responsible for the damages that could be incurred. The Company is in no way, shape, or form associated with Tabroom.com or the National Speech and Debate association. All information pulled is publicly available. This program was written by Samarth Chitgopekar, the CTO of Offtime Roadmap, LLC. See https://github.com/http-samc for the Source Code to the Software and more. By using the Software to any extent, you agree to these terms and conditions."))
        self.pushButton_2.setText(_translate("MainWindow", "Need Help? Click here to Read the Docs"))


import sys
app = QtWidgets.QApplication(sys.argv)
qtmodern.styles.dark(app)

MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()

ui.setupUi(MainWindow)

MainWindow = qtmodern.windows.ModernWindow(MainWindow)

MainWindow.show()
sys.exit(app.exec_())