from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame, QMainWindow

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setObjectName("self")
        self.resize(1080, 630)
        self.setMinimumSize(QtCore.QSize(1080, 630))
        self.central_grid_layout = QtWidgets.QWidget(self)
        self.central_grid_layout.setObjectName("central_grid_layout")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.central_grid_layout)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tab_master = QtWidgets.QTabWidget(self.central_grid_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_master.sizePolicy().hasHeightForWidth())
        self.tab_master.setSizePolicy(sizePolicy)
        self.tab_master.setMinimumSize(QtCore.QSize(775, 400))
        self.tab_master.setStyleSheet("QTabWidget::tab-bar {\n"
        "            alignment: center;\n"
        "}")
        self.tab_master.setObjectName("tab_master")
        self.about_tab = QtWidgets.QWidget()
        self.about_tab.setObjectName("about_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.about_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.distro = QtWidgets.QTextEdit(self.about_tab)
        self.distro.setMaximumSize(QtCore.QSize(16777215, 1677770))
        self.distro.setReadOnly(True)
        self.distro.setObjectName("distro")
        self.verticalLayout_2.addWidget(self.distro)
        self.tab_master.addTab(self.about_tab, "")
        self.home_tab = QtWidgets.QWidget()
        self.home_tab.setObjectName("home_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.home_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.home_options_layout = QtWidgets.QVBoxLayout()
        self.home_options_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.home_options_layout.setContentsMargins(0, -1, -1, 0)
        self.home_options_layout.setSpacing(0)
        self.home_options_layout.setObjectName("home_options_layout")
        self.card_info_box = QtWidgets.QGroupBox(self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.card_info_box.sizePolicy().hasHeightForWidth())
        self.card_info_box.setSizePolicy(sizePolicy)
        self.card_info_box.setMinimumSize(QtCore.QSize(355, 110))
        self.card_info_box.setStyleSheet("")
        self.card_info_box.setObjectName("card_info_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.card_info_box)
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.link = QtWidgets.QLineEdit(self.card_info_box)
        self.link.setMinimumSize(QtCore.QSize(0, 20))
        self.link.setMaximumSize(QtCore.QSize(16777215, 20))
        self.link.setObjectName("link")
        self.gridLayout_4.addWidget(self.link, 4, 0, 1, 1)
        self.creds = QtWidgets.QLineEdit(self.card_info_box)
        self.creds.setMinimumSize(QtCore.QSize(0, 20))
        self.creds.setMaximumSize(QtCore.QSize(16777215, 20))
        self.creds.setObjectName("creds")
        self.gridLayout_4.addWidget(self.creds, 3, 0, 1, 1)
        self.warrant = QtWidgets.QLineEdit(self.card_info_box)
        self.warrant.setMinimumSize(QtCore.QSize(0, 20))
        self.warrant.setMaximumSize(QtCore.QSize(16777215, 20))
        self.warrant.setObjectName("warrant")
        self.gridLayout_4.addWidget(self.warrant, 2, 0, 1, 1)
        self.home_options_layout.addWidget(self.card_info_box)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.home_options_layout.addItem(spacerItem)
        self.options_box = QtWidgets.QGroupBox(self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_box.sizePolicy().hasHeightForWidth())
        self.options_box.setSizePolicy(sizePolicy)
        self.options_box.setMinimumSize(QtCore.QSize(355, 90))
        self.options_box.setMaximumSize(QtCore.QSize(275, 70))
        self.options_box.setObjectName("options_box")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.options_box)
        self.gridLayout_10.setContentsMargins(-1, -1, -1, 15)
        self.gridLayout_10.setVerticalSpacing(10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.autocut = QtWidgets.QPushButton(self.options_box)
        self.autocut.setMinimumSize(QtCore.QSize(15, 20))
        self.autocut.setMaximumSize(QtCore.QSize(16777215, 15))
        self.autocut.setFocusPolicy(QtCore.Qt.NoFocus)
        self.autocut.setText("")
        self.autocut.setObjectName("autocut")
        self.gridLayout_10.addWidget(self.autocut, 0, 4, 1, 1, QtCore.Qt.AlignTop)
        self.label = QtWidgets.QLabel(self.options_box)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 1, 1, 1)
        self.autobypass = QtWidgets.QPushButton(self.options_box)
        self.autobypass.setMinimumSize(QtCore.QSize(335, 25))
        self.autobypass.setObjectName("autobypass")
        self.gridLayout_10.addWidget(self.autobypass, 1, 0, 1, 5)
        self.autocite = QtWidgets.QCheckBox(self.options_box)
        self.autocite.setMinimumSize(QtCore.QSize(0, 20))
        self.autocite.setMaximumSize(QtCore.QSize(15, 15))
        self.autocite.setFocusPolicy(QtCore.Qt.NoFocus)
        self.autocite.setText("")
        self.autocite.setChecked(True)
        self.autocite.setObjectName("autocite")
        self.gridLayout_10.addWidget(self.autocite, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.autopoll = QtWidgets.QCheckBox(self.options_box)
        self.autopoll.setMinimumSize(QtCore.QSize(0, 20))
        self.autopoll.setMaximumSize(QtCore.QSize(15, 15))
        self.autopoll.setFocusPolicy(QtCore.Qt.NoFocus)
        self.autopoll.setText("")
        self.autopoll.setChecked(True)
        self.autopoll.setObjectName("autopoll")
        self.gridLayout_10.addWidget(self.autopoll, 0, 2, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(self.options_box)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 0, 3, 1, 1)
        self.home_options_layout.addWidget(self.options_box)
        spacerItem1 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.home_options_layout.addItem(spacerItem1)
        self.cut_it_box = QtWidgets.QGroupBox(self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cut_it_box.sizePolicy().hasHeightForWidth())
        self.cut_it_box.setSizePolicy(sizePolicy)
        self.cut_it_box.setMinimumSize(QtCore.QSize(355, 125))
        self.cut_it_box.setMaximumSize(QtCore.QSize(275, 100))
        self.cut_it_box.setObjectName("cut_it_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.cut_it_box)
        self.gridLayout_5.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.primary_em = QtWidgets.QPushButton(self.cut_it_box)
        self.primary_em.setMinimumSize(QtCore.QSize(0, 25))
        self.primary_em.setMaximumSize(QtCore.QSize(16777215, 25))
        self.primary_em.setFocusPolicy(QtCore.Qt.NoFocus)
        self.primary_em.setStyleSheet("")
        self.primary_em.setObjectName("primary_em")
        self.gridLayout_5.addWidget(self.primary_em, 0, 5, 1, 2)
        self.primary_highlight = QtWidgets.QPushButton(self.cut_it_box)
        self.primary_highlight.setMinimumSize(QtCore.QSize(0, 25))
        self.primary_highlight.setMaximumSize(QtCore.QSize(16777215, 25))
        self.primary_highlight.setFocusPolicy(QtCore.Qt.NoFocus)
        self.primary_highlight.setObjectName("primary_highlight")
        self.gridLayout_5.addWidget(self.primary_highlight, 1, 8, 1, 1)
        self.underline = QtWidgets.QPushButton(self.cut_it_box)
        self.underline.setMinimumSize(QtCore.QSize(0, 25))
        self.underline.setMaximumSize(QtCore.QSize(16777215, 25))
        self.underline.setFocusPolicy(QtCore.Qt.NoFocus)
        self.underline.setObjectName("underline")
        self.gridLayout_5.addWidget(self.underline, 1, 6, 1, 1)
        self.secondary_em = QtWidgets.QPushButton(self.cut_it_box)
        self.secondary_em.setMinimumSize(QtCore.QSize(0, 25))
        self.secondary_em.setMaximumSize(QtCore.QSize(16777215, 25))
        self.secondary_em.setFocusPolicy(QtCore.Qt.NoFocus)
        self.secondary_em.setObjectName("secondary_em")
        self.gridLayout_5.addWidget(self.secondary_em, 0, 7, 1, 2)
        self.minimize = QtWidgets.QPushButton(self.cut_it_box)
        self.minimize.setMinimumSize(QtCore.QSize(0, 25))
        self.minimize.setMaximumSize(QtCore.QSize(16777215, 25))
        self.minimize.setFocusPolicy(QtCore.Qt.NoFocus)
        self.minimize.setObjectName("minimize")
        self.gridLayout_5.addWidget(self.minimize, 1, 10, 1, 1)
        self.tertiary_em = QtWidgets.QPushButton(self.cut_it_box)
        self.tertiary_em.setMinimumSize(QtCore.QSize(0, 25))
        self.tertiary_em.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tertiary_em.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tertiary_em.setObjectName("tertiary_em")
        self.gridLayout_5.addWidget(self.tertiary_em, 0, 9, 1, 2)
        self.clearSelectionFormatting = QtWidgets.QPushButton(self.cut_it_box)
        self.clearSelectionFormatting.setMinimumSize(QtCore.QSize(0, 25))
        self.clearSelectionFormatting.setMaximumSize(QtCore.QSize(16777215, 25))
        self.clearSelectionFormatting.setObjectName("clearSelectionFormatting")
        self.gridLayout_5.addWidget(self.clearSelectionFormatting, 2, 5, 1, 6)
        self.bold = QtWidgets.QPushButton(self.cut_it_box)
        self.bold.setMinimumSize(QtCore.QSize(0, 25))
        self.bold.setMaximumSize(QtCore.QSize(16777215, 25))
        self.bold.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bold.setObjectName("bold")
        self.gridLayout_5.addWidget(self.bold, 1, 5, 1, 1)
        self.secondary_highlight = QtWidgets.QPushButton(self.cut_it_box)
        self.secondary_highlight.setMinimumSize(QtCore.QSize(0, 25))
        self.secondary_highlight.setMaximumSize(QtCore.QSize(16777215, 25))
        self.secondary_highlight.setFocusPolicy(QtCore.Qt.NoFocus)
        self.secondary_highlight.setObjectName("secondary_highlight")
        self.gridLayout_5.addWidget(self.secondary_highlight, 1, 9, 1, 1)
        self.italics = QtWidgets.QPushButton(self.cut_it_box)
        self.italics.setMinimumSize(QtCore.QSize(0, 25))
        self.italics.setMaximumSize(QtCore.QSize(16777215, 25))
        self.italics.setFocusPolicy(QtCore.Qt.NoFocus)
        self.italics.setObjectName("italics")
        self.gridLayout_5.addWidget(self.italics, 1, 7, 1, 1)
        self.home_options_layout.addWidget(self.cut_it_box)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.home_options_layout.addItem(spacerItem2)
        self.card_history = QtWidgets.QGroupBox(self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.card_history.sizePolicy().hasHeightForWidth())
        self.card_history.setSizePolicy(sizePolicy)
        self.card_history.setMinimumSize(QtCore.QSize(355, 90))
        self.card_history.setMaximumSize(QtCore.QSize(275, 65))
        self.card_history.setObjectName("card_history")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.card_history)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_2.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.home_options_layout.addWidget(self.card_history)
        spacerItem3 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.home_options_layout.addItem(spacerItem3)
        self.msg = QtWidgets.QTextEdit(self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msg.sizePolicy().hasHeightForWidth())
        self.msg.setSizePolicy(sizePolicy)
        self.msg.setMinimumSize(QtCore.QSize(355, 55))
        self.msg.setMaximumSize(QtCore.QSize(275, 55))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.msg.setFont(font)
        self.msg.setStyleSheet("font-size: 13pt;")
        self.msg.setReadOnly(True)
        self.msg.setObjectName("msg")
        self.home_options_layout.addWidget(self.msg)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.home_options_layout.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.home_options_layout)
        self.evidence_box = QtWidgets.QPlainTextEdit(self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evidence_box.sizePolicy().hasHeightForWidth())
        self.evidence_box.setSizePolicy(sizePolicy)
        self.evidence_box.setMinimumSize(QtCore.QSize(650, 355))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.evidence_box.setFont(font)
        self.evidence_box.setStyleSheet("border-radius: 15px;")
        self.evidence_box.setObjectName("evidence_box")
        self.horizontalLayout_3.addWidget(self.evidence_box)
        self.tab_master.addTab(self.home_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.settings_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.misc_box = QtWidgets.QGroupBox(self.settings_tab)
        self.misc_box.setStyleSheet("")
        self.misc_box.setObjectName("misc_box")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.misc_box)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.feedback = QtWidgets.QTextEdit(self.misc_box)
        self.feedback.setStyleSheet("")
        self.feedback.setObjectName("feedback")
        self.gridLayout_8.addWidget(self.feedback, 2, 0, 1, 1)
        self.submit_feedback = QtWidgets.QPushButton(self.misc_box)
        self.submit_feedback.setStyleSheet("")
        self.submit_feedback.setObjectName("submit_feedback")
        self.gridLayout_8.addWidget(self.submit_feedback, 3, 0, 1, 1)
        self.theme = QtWidgets.QPushButton(self.misc_box)
        self.theme.setStyleSheet("")
        self.theme.setObjectName("theme")
        self.gridLayout_8.addWidget(self.theme, 0, 0, 1, 1)
        self.updates = QtWidgets.QPushButton(self.misc_box)
        self.updates.setObjectName("updates")
        self.gridLayout_8.addWidget(self.updates, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.misc_box, 1, 1, 1, 1)
        self.pref_box = QtWidgets.QGroupBox(self.settings_tab)
        self.pref_box.setStyleSheet("")
        self.pref_box.setObjectName("pref_box")
        self.gridLayout = QtWidgets.QGridLayout(self.pref_box)
        self.gridLayout.setObjectName("gridLayout")
        self.zoom_label = QtWidgets.QLabel(self.pref_box)
        self.zoom_label.setObjectName("zoom_label")
        self.gridLayout.addWidget(self.zoom_label, 3, 0, 1, 1)
        self.highlight_2_label = QtWidgets.QLabel(self.pref_box)
        self.highlight_2_label.setObjectName("highlight_2_label")
        self.gridLayout.addWidget(self.highlight_2_label, 5, 0, 1, 1)
        self.highlight_2 = QtWidgets.QComboBox(self.pref_box)
        self.highlight_2.setObjectName("highlight_2")
        self.highlight_2.addItem("")
        self.highlight_2.addItem("")
        self.highlight_2.addItem("")
        self.highlight_2.addItem("")
        self.highlight_2.addItem("")
        self.highlight_2.addItem("")
        self.gridLayout.addWidget(self.highlight_2, 5, 1, 1, 1)
        self.font_size_min = QtWidgets.QSpinBox(self.pref_box)
        self.font_size_min.setMinimum(1)
        self.font_size_min.setMaximum(24)
        self.font_size_min.setObjectName("font_size_min")
        self.gridLayout.addWidget(self.font_size_min, 2, 1, 1, 1)
        self.font = QtWidgets.QComboBox(self.pref_box)
        self.font.setObjectName("font")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.font.addItem("")
        self.gridLayout.addWidget(self.font, 0, 1, 1, 1)
        self.highlight_1 = QtWidgets.QComboBox(self.pref_box)
        self.highlight_1.setObjectName("highlight_1")
        self.highlight_1.addItem("")
        self.highlight_1.addItem("")
        self.highlight_1.addItem("")
        self.highlight_1.addItem("")
        self.highlight_1.addItem("")
        self.highlight_1.addItem("")
        self.gridLayout.addWidget(self.highlight_1, 4, 1, 1, 1)
        self.font_size_normal = QtWidgets.QSpinBox(self.pref_box)
        self.font_size_normal.setMinimum(1)
        self.font_size_normal.setMaximum(24)
        self.font_size_normal.setObjectName("font_size_normal")
        self.gridLayout.addWidget(self.font_size_normal, 1, 1, 1, 1)
        self.PrimaryEmSettings = QtWidgets.QGroupBox(self.pref_box)
        self.PrimaryEmSettings.setMinimumSize(QtCore.QSize(0, 80))
        self.PrimaryEmSettings.setMaximumSize(QtCore.QSize(16777215, 80))
        self.PrimaryEmSettings.setObjectName("PrimaryEmSettings")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.PrimaryEmSettings)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.primary_bold = QtWidgets.QCheckBox(self.PrimaryEmSettings)
        self.primary_bold.setObjectName("primary_bold")
        self.horizontalLayout_4.addWidget(self.primary_bold)
        self.primary_underline = QtWidgets.QCheckBox(self.PrimaryEmSettings)
        self.primary_underline.setTristate(False)
        self.primary_underline.setObjectName("primary_underline")
        self.horizontalLayout_4.addWidget(self.primary_underline)
        self.primary_italicised = QtWidgets.QCheckBox(self.PrimaryEmSettings)
        self.primary_italicised.setObjectName("primary_italicised")
        self.horizontalLayout_4.addWidget(self.primary_italicised)
        self.primary_highlight_2 = QtWidgets.QComboBox(self.PrimaryEmSettings)
        self.primary_highlight_2.setObjectName("primary_highlight_2")
        self.primary_highlight_2.addItem("")
        self.primary_highlight_2.addItem("")
        self.primary_highlight_2.addItem("")
        self.primary_highlight_2.addItem("")
        self.primary_highlight_2.addItem("")
        self.primary_highlight_2.addItem("")
        self.primary_highlight_2.addItem("")
        self.horizontalLayout_4.addWidget(self.primary_highlight_2)
        self.primary_size = QtWidgets.QSpinBox(self.PrimaryEmSettings)
        self.primary_size.setMinimum(1)
        self.primary_size.setMaximum(26)
        self.primary_size.setObjectName("primary_size")
        self.horizontalLayout_4.addWidget(self.primary_size)
        self.gridLayout.addWidget(self.PrimaryEmSettings, 6, 0, 1, 2)
        self.SecondaryEmSettings = QtWidgets.QGroupBox(self.pref_box)
        self.SecondaryEmSettings.setMinimumSize(QtCore.QSize(0, 80))
        self.SecondaryEmSettings.setMaximumSize(QtCore.QSize(16777215, 80))
        self.SecondaryEmSettings.setObjectName("SecondaryEmSettings")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.SecondaryEmSettings)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.secondary_bold = QtWidgets.QCheckBox(self.SecondaryEmSettings)
        self.secondary_bold.setObjectName("secondary_bold")
        self.horizontalLayout_5.addWidget(self.secondary_bold)
        self.secondary_underline = QtWidgets.QCheckBox(self.SecondaryEmSettings)
        self.secondary_underline.setObjectName("secondary_underline")
        self.horizontalLayout_5.addWidget(self.secondary_underline)
        self.secondary_italicised = QtWidgets.QCheckBox(self.SecondaryEmSettings)
        self.secondary_italicised.setObjectName("secondary_italicised")
        self.horizontalLayout_5.addWidget(self.secondary_italicised)
        self.secondary_highlight_2 = QtWidgets.QComboBox(self.SecondaryEmSettings)
        self.secondary_highlight_2.setObjectName("secondary_highlight_2")
        self.secondary_highlight_2.addItem("")
        self.secondary_highlight_2.addItem("")
        self.secondary_highlight_2.addItem("")
        self.secondary_highlight_2.addItem("")
        self.secondary_highlight_2.addItem("")
        self.secondary_highlight_2.addItem("")
        self.secondary_highlight_2.addItem("")
        self.horizontalLayout_5.addWidget(self.secondary_highlight_2)
        self.secondary_size = QtWidgets.QSpinBox(self.SecondaryEmSettings)
        self.secondary_size.setMinimum(1)
        self.secondary_size.setMaximum(26)
        self.secondary_size.setObjectName("secondary_size")
        self.horizontalLayout_5.addWidget(self.secondary_size)
        self.gridLayout.addWidget(self.SecondaryEmSettings, 7, 0, 1, 2)
        self.highlight_1_label = QtWidgets.QLabel(self.pref_box)
        self.highlight_1_label.setObjectName("highlight_1_label")
        self.gridLayout.addWidget(self.highlight_1_label, 4, 0, 1, 1)
        self.zoom = QtWidgets.QSpinBox(self.pref_box)
        self.zoom.setObjectName("zoom")
        self.gridLayout.addWidget(self.zoom, 3, 1, 1, 1)
        self.warning = QtWidgets.QLineEdit(self.pref_box)
        self.warning.setStyleSheet("")
        self.warning.setAlignment(QtCore.Qt.AlignCenter)
        self.warning.setReadOnly(True)
        self.warning.setObjectName("warning")
        self.gridLayout.addWidget(self.warning, 10, 0, 1, 2)
        self.TertiaryEmSettings = QtWidgets.QGroupBox(self.pref_box)
        self.TertiaryEmSettings.setMinimumSize(QtCore.QSize(0, 80))
        self.TertiaryEmSettings.setMaximumSize(QtCore.QSize(16777215, 80))
        self.TertiaryEmSettings.setObjectName("TertiaryEmSettings")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.TertiaryEmSettings)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tertiary_bold = QtWidgets.QCheckBox(self.TertiaryEmSettings)
        self.tertiary_bold.setObjectName("tertiary_bold")
        self.horizontalLayout_6.addWidget(self.tertiary_bold)
        self.tertiary_underline = QtWidgets.QCheckBox(self.TertiaryEmSettings)
        self.tertiary_underline.setObjectName("tertiary_underline")
        self.horizontalLayout_6.addWidget(self.tertiary_underline)
        self.tertiary_italicised = QtWidgets.QCheckBox(self.TertiaryEmSettings)
        self.tertiary_italicised.setObjectName("tertiary_italicised")
        self.horizontalLayout_6.addWidget(self.tertiary_italicised)
        self.tertiary_highlight = QtWidgets.QComboBox(self.TertiaryEmSettings)
        self.tertiary_highlight.setObjectName("tertiary_highlight")
        self.tertiary_highlight.addItem("")
        self.tertiary_highlight.addItem("")
        self.tertiary_highlight.addItem("")
        self.tertiary_highlight.addItem("")
        self.tertiary_highlight.addItem("")
        self.tertiary_highlight.addItem("")
        self.tertiary_highlight.addItem("")
        self.horizontalLayout_6.addWidget(self.tertiary_highlight)
        self.tertiary_size = QtWidgets.QSpinBox(self.TertiaryEmSettings)
        self.tertiary_size.setMinimum(1)
        self.tertiary_size.setMaximum(26)
        self.tertiary_size.setObjectName("tertiary_size")
        self.horizontalLayout_6.addWidget(self.tertiary_size)
        self.gridLayout.addWidget(self.TertiaryEmSettings, 8, 0, 1, 2)
        self.font_size_min_label = QtWidgets.QLabel(self.pref_box)
        self.font_size_min_label.setStyleSheet("")
        self.font_size_min_label.setObjectName("font_size_min_label")
        self.gridLayout.addWidget(self.font_size_min_label, 2, 0, 1, 1)
        self.font_size_normal_label = QtWidgets.QLabel(self.pref_box)
        self.font_size_normal_label.setStyleSheet("")
        self.font_size_normal_label.setObjectName("font_size_normal_label")
        self.gridLayout.addWidget(self.font_size_normal_label, 1, 0, 1, 1)
        self.font_label = QtWidgets.QLabel(self.pref_box)
        self.font_label.setStyleSheet("")
        self.font_label.setObjectName("font_label")
        self.gridLayout.addWidget(self.font_label, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 11, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 9, 0, 1, 2)
        self.gridLayout_6.addWidget(self.pref_box, 0, 0, 2, 1)
        self.short_box = QtWidgets.QGroupBox(self.settings_tab)
        self.short_box.setStyleSheet("")
        self.short_box.setObjectName("short_box")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.short_box)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.shortcut_input = QtWidgets.QKeySequenceEdit(self.short_box)
        self.shortcut_input.setObjectName("shortcut_input")
        self.gridLayout_9.addWidget(self.shortcut_input, 1, 0, 1, 1)
        self.shortcuts = QtWidgets.QComboBox(self.short_box)
        self.shortcuts.setPlaceholderText("")
        self.shortcuts.setObjectName("shortcuts")
        self.shortcuts.addItem("")
        self.gridLayout_9.addWidget(self.shortcuts, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.short_box, 0, 1, 1, 1)
        self.tab_master.addTab(self.settings_tab, "")
        self.gridLayout_3.addWidget(self.tab_master, 0, 0, 1, 1)
        self.setCentralWidget(self.central_grid_layout)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        self.tab_master.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.distro.setHtml(_translate("self", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica Neue\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tab_master.setTabText(self.tab_master.indexOf(self.about_tab), _translate("self", "About"))
        self.card_info_box.setTitle(_translate("self", "Card Information"))
        self.link.setPlaceholderText(_translate("self", "URL"))
        self.creds.setPlaceholderText(_translate("self", "Credentials"))
        self.warrant.setPlaceholderText(_translate("self", "Tagline"))
        self.options_box.setTitle(_translate("self", "AutoCut"))
        self.label.setText(_translate("self", "AutoCite"))
        self.autobypass.setText(_translate("self", " Launch SuperBrowser"))
        self.label_2.setText(_translate("self", "AutoPoll"))
        self.cut_it_box.setTitle(_translate("self", "Cut-It"))
        self.primary_em.setText(_translate("self", "Primary Emphasis"))
        self.primary_highlight.setText(_translate("self", "H¹"))
        self.underline.setText(_translate("self", "U"))
        self.secondary_em.setText(_translate("self", "Secondary Emphasis"))
        self.minimize.setText(_translate("self", "M"))
        self.tertiary_em.setText(_translate("self", "Tertiary Emphasis"))
        self.clearSelectionFormatting.setText(_translate("self", "Clear Selection Formatting"))
        self.bold.setText(_translate("self", "B"))
        self.secondary_highlight.setText(_translate("self", "H²"))
        self.italics.setText(_translate("self", "I"))
        self.card_history.setTitle(_translate("self", "Card History"))
        self.msg.setHtml(_translate("self", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica Neue\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.evidence_box.setWhatsThis(_translate("self", "Evidence"))
        self.evidence_box.setPlaceholderText(_translate("self", "Evidence"))
        self.tab_master.setTabText(self.tab_master.indexOf(self.home_tab), _translate("self", "Home"))
        self.misc_box.setTitle(_translate("self", "Miscellaneous"))
        self.feedback.setHtml(_translate("self", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica Neue\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.feedback.setPlaceholderText(_translate("self", "Bugs? Feature Requests? Tokens of appreciation? Let us know here! Please leave your email if you\'re reporting a bug so we can follow up if needed."))
        self.submit_feedback.setText(_translate("self", "Submit Feedback "))
        self.theme.setText(_translate("self", "Toggle Theme"))
        self.updates.setText(_translate("self", "Check for Updates"))
        self.pref_box.setTitle(_translate("self", "Preferences"))
        self.zoom_label.setText(_translate("self", "Text Zoom (only works on new cards) "))
        self.highlight_2_label.setText(_translate("self", "Highlight Color #2"))
        self.highlight_2.setItemText(0, _translate("self", "Green"))
        self.highlight_2.setItemText(1, _translate("self", "Cyan"))
        self.highlight_2.setItemText(2, _translate("self", "Magenta"))
        self.highlight_2.setItemText(3, _translate("self", "Blue"))
        self.highlight_2.setItemText(4, _translate("self", "Purple"))
        self.highlight_2.setItemText(5, _translate("self", "Yellow"))
        self.font_size_min.setSpecialValueText(_translate("self", "4"))
        self.font.setItemText(0, _translate("self", "Arial"))
        self.font.setItemText(1, _translate("self", "Arial Narrow"))
        self.font.setItemText(2, _translate("self", "Calibri"))
        self.font.setItemText(3, _translate("self", "Cambria"))
        self.font.setItemText(4, _translate("self", "Candara"))
        self.font.setItemText(5, _translate("self", "Courier New"))
        self.font.setItemText(6, _translate("self", "Copperplate"))
        self.font.setItemText(7, _translate("self", "Didot"))
        self.font.setItemText(8, _translate("self", "Geneva"))
        self.font.setItemText(9, _translate("self", "Georgia"))
        self.font.setItemText(10, _translate("self", "Garamond"))
        self.font.setItemText(11, _translate("self", "Helvetica"))
        self.font.setItemText(12, _translate("self", "Lucida Bright"))
        self.font.setItemText(13, _translate("self", "Optima"))
        self.font.setItemText(14, _translate("self", "Perpetua"))
        self.font.setItemText(15, _translate("self", "Times"))
        self.font.setItemText(16, _translate("self", "Tahoma"))
        self.font.setItemText(17, _translate("self", "Trebuchet MS"))
        self.font.setItemText(18, _translate("self", "Times New Roman"))
        self.font.setItemText(19, _translate("self", "Verdana"))
        self.highlight_1.setItemText(0, _translate("self", "Green"))
        self.highlight_1.setItemText(1, _translate("self", "Cyan"))
        self.highlight_1.setItemText(2, _translate("self", "Magenta"))
        self.highlight_1.setItemText(3, _translate("self", "Blue"))
        self.highlight_1.setItemText(4, _translate("self", "Purple"))
        self.highlight_1.setItemText(5, _translate("self", "Yellow"))
        self.font_size_normal.setSpecialValueText(_translate("self", "12"))
        self.PrimaryEmSettings.setTitle(_translate("self", "Primary Emphasis"))
        self.primary_bold.setText(_translate("self", "Bold"))
        self.primary_underline.setText(_translate("self", "Underline"))
        self.primary_italicised.setText(_translate("self", "Italicised"))
        self.primary_highlight_2.setItemText(0, _translate("self", "None"))
        self.primary_highlight_2.setItemText(1, _translate("self", "Green"))
        self.primary_highlight_2.setItemText(2, _translate("self", "Cyan"))
        self.primary_highlight_2.setItemText(3, _translate("self", "Magenta"))
        self.primary_highlight_2.setItemText(4, _translate("self", "Blue"))
        self.primary_highlight_2.setItemText(5, _translate("self", "Purple"))
        self.primary_highlight_2.setItemText(6, _translate("self", "Yellow"))
        self.primary_size.setSpecialValueText(_translate("self", "16"))
        self.SecondaryEmSettings.setTitle(_translate("self", "Secondary Emphasis"))
        self.secondary_bold.setText(_translate("self", "Bold"))
        self.secondary_underline.setText(_translate("self", "Underline"))
        self.secondary_italicised.setText(_translate("self", "Italicised"))
        self.secondary_highlight_2.setItemText(0, _translate("self", "None"))
        self.secondary_highlight_2.setItemText(1, _translate("self", "Green"))
        self.secondary_highlight_2.setItemText(2, _translate("self", "Cyan"))
        self.secondary_highlight_2.setItemText(3, _translate("self", "Magenta"))
        self.secondary_highlight_2.setItemText(4, _translate("self", "Blue"))
        self.secondary_highlight_2.setItemText(5, _translate("self", "Purple"))
        self.secondary_highlight_2.setItemText(6, _translate("self", "Yellow"))
        self.secondary_size.setSpecialValueText(_translate("self", "16"))
        self.highlight_1_label.setText(_translate("self", "Highlight Color #1"))
        self.warning.setText(_translate("self", "‼️ Any changes made here will apply on the next restart ‼️"))
        self.TertiaryEmSettings.setTitle(_translate("self", "Tertiary Emphasis"))
        self.tertiary_bold.setText(_translate("self", "Bold"))
        self.tertiary_underline.setText(_translate("self", "Underline"))
        self.tertiary_italicised.setText(_translate("self", "Italicised"))
        self.tertiary_highlight.setItemText(0, _translate("self", "None"))
        self.tertiary_highlight.setItemText(1, _translate("self", "Green"))
        self.tertiary_highlight.setItemText(2, _translate("self", "Cyan"))
        self.tertiary_highlight.setItemText(3, _translate("self", "Magenta"))
        self.tertiary_highlight.setItemText(4, _translate("self", "Blue"))
        self.tertiary_highlight.setItemText(5, _translate("self", "Purple"))
        self.tertiary_highlight.setItemText(6, _translate("self", "Yellow"))
        self.tertiary_size.setSpecialValueText(_translate("self", "16"))
        self.font_size_min_label.setText(_translate("self", "Font Size of Minimized Text"))
        self.font_size_normal_label.setText(_translate("self", "Font Size of Normal Text"))
        self.font_label.setText(_translate("self", "Font"))
        self.short_box.setTitle(_translate("self", "Shortcuts"))
        self.shortcuts.setItemText(0, _translate("self", "Choose a shortcut to view/edit . . . (applies on restart)"))
        self.tab_master.setTabText(self.tab_master.indexOf(self.settings_tab), _translate("self", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mw = MainWindow()
    mw.show()
    sys.exit(app.exec_())